language: ruby

rvm:
  - 2.3.3

install: gem install jekyll html-proofer jekyll-theme-tactile

script: jekyll build && htmlproofer ./_site

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false